// src/app/timer/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { Duration } from "luxon";
import {
  CaretDownIcon,
  CaretUpIcon,
  PauseIcon,
  PlayIcon,
  PlusOneIcon,
  ResetIcon,
} from "@/lib/icons";
import Layout from "@/components/Layout";

const INITIAL_MSG = "Swipe Up/Down to Set Timer";

export default function Page() {
  const [duration, setDuration] = useState(Duration.fromMillis(0));
  const [isRunning, setIsRunning] = useState(false);
  const [started, setStarted] = useState(false);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);
  const [message, setMessage] = useState(INITIAL_MSG);

  function update(unit: any, delta: number) {
    if (isRunning || started) return;

    let newDuration = duration.plus({ [unit]: delta });
    if (newDuration.get(unit) < 0) {
      newDuration = newDuration.set({ [unit]: 0 });
    } else if (newDuration.get(unit) > 59) {
      newDuration = newDuration.set({ [unit]: 59 });
    }
    setDuration(newDuration);
  }

  function updateOnWheel(e: React.WheelEvent<HTMLSpanElement>, unit: any) {
    const delta = e.deltaY > 0 ? 1 : -1;
    update(unit, delta);
  }

  function updateOnTouch(e: React.TouchEvent<HTMLSpanElement>, unit: any) {
    const touchMoveY = e.touches[0].clientY;
    let delta = 0;

    if (e.type === "touchstart") {
      e.currentTarget.dataset.touchStartY = touchMoveY.toString();
    } else if (e.type === "touchmove") {
      const touchStartY = parseFloat(
        e.currentTarget.dataset.touchStartY || "0",
      );
      delta = touchMoveY - touchStartY;

      if (Math.abs(delta) > 10) {
        update(unit, delta > 0 ? -1 : 1);
        e.currentTarget.dataset.touchStartY = touchMoveY.toString();
      }
    }
  }

  function toggleTimer() {
    if (duration.as("seconds") <= 0) return;
    setStarted(true);
    setIsRunning((prev) => !prev);
  }

  useEffect(() => {
    if (isRunning) {
      intervalRef.current = setInterval(() => {
        setDuration((prevDur) => {
          const newDur = prevDur.minus(1000);
          if (newDur.as("seconds") <= 0) {
            endTimer();
            return prevDur;
          }
          return newDur;
        });
      }, 1000);
      setMessage("Timer Running...");
    } else {
      clearInterval(intervalRef.current!);
      started && setMessage("Timer Paused");
    }

    return () => {
      clearInterval(intervalRef.current!);
    };
  }, [isRunning, started]);

  // UPDATE TITLE
  useEffect(() => {
    if (isRunning) {
      document.title = `Timer ${
        duration.hours > 0
          ? duration.toFormat("hh:mm:ss")
          : duration.toFormat("mm:ss")
      }`;
    } else {
      document.title = "Timer";
    }
  }, [duration, isRunning]);

  function reset() {
    if (isRunning) return;
    setDuration(Duration.fromMillis(0));
    setStarted(false);
    setMessage(INITIAL_MSG);
  }

  function plusOne() {
    setDuration((prevDur) => prevDur.plus({ minutes: 1 }));
  }

  function endTimer() {
    setDuration(Duration.fromMillis(0));
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
    }
    setStarted(false);
    setIsRunning(false);
    setMessage("Timer Ended");
  }

  return (
    <Layout
      top={message}
      mid={
        <Mid
          duration={duration}
          update={update}
          updateOnWheel={updateOnWheel}
          updateOnTouch={updateOnTouch}
          started={started}
        />
      }
      bottom={
        <Bottom
          isRunning={isRunning}
          reset={reset}
          duration={duration}
          toggleTimer={toggleTimer}
          plusOne={plusOne}
        />
      }
    />
  );
}

function Mid({
  duration,
  update,
  updateOnWheel,
  updateOnTouch,
  started,
}: {
  duration: Duration;
  update: (unit: any, delta: number) => void;
  updateOnWheel: (e: React.WheelEvent<HTMLSpanElement>, unit: any) => void;
  updateOnTouch: (e: React.TouchEvent<HTMLSpanElement>, unit: any) => void;
  started: boolean;
}) {
  return (
    <>
      {["hours", "minutes", "seconds"].map((unit, i) => (
        <span key={i} className="">
          <span className="relative group">
            <button
              className={`absolute -top-0 left-1/2 -translate-x-1/2 px-6 group-hover:block lg:hidden ${
                started ? "hidden" : "cursor-pointer"
              }`}
              onClick={() => update(unit, 1)}
            >
              <CaretUpIcon />
            </button>
            <span
              className={started ? "cursor-not-allowed" : "cursor-ns-resize"}
              onWheel={(e) => updateOnWheel(e, unit)}
              onTouchStart={(e) => updateOnTouch(e, unit)}
              onTouchMove={(e) => updateOnTouch(e, unit)}
            >
              {duration.toFormat("hh:mm:ss").split(":")[i]}
            </span>
            <button
              className={`absolute -bottom-0 left-1/2 -translate-x-1/2 px-6 group-hover:block lg:hidden ${
                started ? "hidden" : "cursor-pointer"
              }`}
              onClick={() => update(unit, -1)}
            >
              <CaretDownIcon />
            </button>
          </span>
          {unit !== "seconds" && <span>:</span>}
        </span>
      ))}
    </>
  );
}

function Bottom({
  isRunning,
  reset,
  duration,
  toggleTimer,
  plusOne,
}: {
  isRunning: boolean;
  reset: () => void;
  duration: Duration;
  toggleTimer: () => void;
  plusOne: () => void;
}) {
  return (
    <div className="flex items-center justify-center gap-12">
      {/* RESET */}
      <button
        className={
          isRunning ? "cursor-not-allowed opacity-50" : "cursor-pointer"
        }
        onClick={reset}
      >
        <ResetIcon size={40} />
      </button>

      {/* PLAY/PAUSE */}
      <button
        className={
          duration.as("seconds") <= 0
            ? "cursor-not-allowed opacity-50"
            : "cursor-pointer"
        }
        onClick={toggleTimer}
      >
        {isRunning ? <PauseIcon size={80} /> : <PlayIcon size={80} />}
      </button>

      {/* +1 MINUTE */}
      <button className="cursor-pointer" onClick={plusOne}>
        <PlusOneIcon size={40} />
      </button>
    </div>
  );
}

// src/routes/timer/+page.svelte
<script lang="ts">
    import { icons } from "$lib/icons";
    import PageStructure from "$lib/PageStructure.svelte";
    import { ts } from "$lib/stores/timer";

    let timer: any;
    $: timer = $ts;

    let su = { unit: "", startY: 0 }; // State for each Unit

    function handleTouch(e: TouchEvent, unit: string) {
        if (timer.started) return; // Do nothing if Timer started

        const currY = e.touches[0].clientY;
        const deltaY = Math.round(su.startY - currY);
        updateUnit(su.unit, deltaY);
    }

    function handleWheel(e: WheelEvent) {
        if (timer.started) return;
        
        updateUnit(su.unit, e.deltaY);
    }

    // SCROLL OVER ANY UNIT TO SET TIMER
    function updateUnit(unit: string, deltaY: number) {
        if (deltaY > 0 && timer.obj.get(unit) < 59) {
            // Scroll Up
            timer.obj = timer.obj.plus({ [unit]: 1 });
        } else if (deltaY < 0 && timer.obj.get(unit) > 0) {
            // Scroll Down untill 0
            timer.obj = timer.obj.minus({ [unit]: 1 });
        }
    }

    // ADD ONE MIN BUTTON, WORKS AT ALL TIMES
    const addMinute = () => (timer.obj = timer.obj.plus({ minutes: 1 }));

    // START OR PAUSE BUTTON
    function playPause() {
        if (timer.obj.as("seconds") <= 0) return;

        timer.running ? ts.pause() : ts.run();
    }
</script>

<svelte:head>
    <title>
        Timer
        { timer.running ? timer.obj.hours > 0 ? timer.obj.toFormat("hh:mm:ss"): timer.obj.toFormat("mm:ss") : '' }
    </title>
    <meta property="og:title" content="Timer - Set and Track Time">
    <meta property="og:description" content="Effortlessly set and manage countdowns with Bigtime's Timer. Scroll to adjust time and stay on top of your tasks.">

    <meta name="twitter:title" content="Timer - Set and Track Time">
    <meta name="twitter:description" content="Effortlessly set and manage countdowns with Bigtime's Timer. Scroll to adjust time and stay on top of your tasks.">
</svelte:head>

<PageStructure>
    <div slot="upper">{timer.message}</div>

    <!-- CLOCK -->
    <div slot="clock" class="flex justify-center">
        <div class="relative group">
            <button
                class="text-3xl absolute -top-5 md:top-0 lg:top-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("hours", 1)}
                >{@html icons.caretUp}</button
            >

            <div
                class={timer.started
                    ? "cursor-not-allowed"
                    : "cursor-ns-resize"}
                on:touchstart={(e) => {
                    su.startY = e.touches[0].clientY;
                    su.unit = "hours";
                }}
                on:touchmove={(e) => handleTouch(e, "hours")}
                on:wheel={(e) => {
                    su.unit = "hours";
                    handleWheel(e);
                }}
            >
                {timer.obj.toFormat("hh:mm:ss").split(":")[0]}
            </div>

            <button
                class="text-3xl absolute -bottom-5 md:bottom-0 lg:bottom-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("hours", -1)}
            >
                {@html icons.caretDown}
            </button>
        </div>
        :
        <div class="relative group">
            <button
                class="text-3xl absolute -top-5 md:top-0 lg:top-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("minutes", 1)}
            >
                {@html icons.caretUp}
            </button>

            <div
                class={timer.started
                    ? "cursor-not-allowed"
                    : "cursor-ns-resize"}
                on:touchstart={(e) => {
                    su.startY = e.touches[0].clientY;
                    su.unit = "minutes";
                }}
                on:touchmove={(e) => handleTouch(e, "minutes")}
                on:wheel={(e) => {
                    su.unit = "minutes";
                    handleWheel(e);
                }}
            >
                {timer.obj.toFormat("hh:mm:ss").split(":")[1]}
            </div>

            <button
                class="text-3xl absolute -bottom-5 md:bottom-0 lg:bottom-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("minutes", -1)}
            >
                {@html icons.caretDown}
            </button>
        </div>
        :
        <div class="relative group">
            <button
                class="text-3xl absolute -top-5 md:top-0 lg:top-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("seconds", 1)}
            >
                {@html icons.caretUp}
            </button>

            <div
                class={timer.started
                    ? "cursor-not-allowed"
                    : "cursor-ns-resize"}
                on:touchstart={(e) => {
                    su.startY = e.touches[0].clientY;
                    su.unit = "seconds";
                }}
                on:touchmove={(e) => handleTouch(e, "seconds")}
                on:wheel={(e) => {
                    su.unit = "seconds";
                    handleWheel(e);
                }}
            >
                {timer.obj.toFormat("hh:mm:ss").split(":")[2]}
            </div>

            <button
                class="text-3xl absolute -bottom-5 md:bottom-0 lg:bottom-5 left-1/2 -translate-x-1/2 hidden group-hover:block"
                on:click={(e) => updateUnit("seconds", -1)}
            >
                {@html icons.caretDown}
            </button>
        </div>
    </div>

    <div slot="lower" class="flex justify-center align-center gap-10 text-4xl">
        <!-- RESET BTN -->
        <button on:click={() => ts.reset()}>{@html icons.reset}</button>

        <!-- PLAY/PAUSE BTN -->
        <button
            class="text-8xl {timer.obj.as('seconds') > 0
                ? 'cursor-pointer'
                : 'cursor-not-allowed'}"
            on:click={playPause}
        >
            {@html timer.running ? icons.pause : icons.play}
        </button>

        <!-- +1 BTN -->
        <button class="" on:click={addMinute}>
            {@html icons.plus1}
        </button>
    </div>
</PageStructure>
